apiVersion: v1
data:
  config.yaml: |
    prometheusK8s:
      remoteWrite:
      - url: http://observatorium-api-gateway-observatorium.apps-crc.testing/api/v1/metrics/write
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
