apiVersion: hive.openshift.io/v1
kind: SyncSet
metadata:
  name: mygroup
spec:
  clusterDeploymentRefs:
  - name: kind-cluster1

  resources:
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    resources:
      - operator-namespace.yaml
      - operator_operatorgroup.yaml
      - operator_catalogsource.yaml
      - operator_subscription.yaml
      - performance_profile.yaml
